# Generated by Django 3.2.7 on 2021-10-03 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.CharField(max_length=200, unique=True)),
                ('photo1', models.ImageField(upload_to='images')),
                ('photo2', models.ImageField(upload_to='images')),
                ('photo3', models.ImageField(upload_to='images')),
                ('auther', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('adventure', 'adventure'), ('art', 'art'), ('contemporary', 'contemporary'), ('cooking', 'cooking'), ('development', 'development'), ('dystopian', 'dystopian'), ('fantasy', 'fantasy'), ('health', 'health'), ('historical_fiction', 'historical fiction'), ('history', 'history'), ('horror', 'horror'), ('humor', 'humor'), ('memoir', 'memoir'), ('motivational', 'motivational'), ('mystery', 'mystery'), ('paranormal', 'paranormal'), ('romance', 'romance'), ('science_fiction', 'science fiction'), ('thriller', 'thriller'), ('travel', 'travel')], max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('number_of_copies', models.IntegerField()),
                ('page1', models.ImageField(upload_to='images')),
                ('page2', models.ImageField(upload_to='images')),
                ('page3', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=100)),
                ('class_of_user', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CreateCombetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='images')),
                ('type_of_combetition', models.CharField(choices=[('story', 'story'), ('poem', 'poem')], max_length=100)),
                ('name_of_combetition', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('min_words', models.IntegerField()),
                ('max_words', models.IntegerField()),
                ('first_prize', models.CharField(max_length=100)),
                ('second_prize', models.CharField(max_length=100)),
                ('third_prize', models.CharField(max_length=100)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_user', models.CharField(max_length=100)),
                ('otp_number', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_return', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RatingAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('rate', models.IntegerField()),
                ('name_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_submit', models.BooleanField(default=False)),
                ('cancel', models.BooleanField(default=False)),
                ('return_order', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_submit', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Combetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('name_of_combetition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.createcombetition')),
                ('name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
                ('name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
